version: '3'

services:
  backend:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
    command: node main
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env.docker
    networks:
      - items-net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - items-net

  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: items
    ports:
      - "5432:5432"
    networks:
      - items-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  items-net:
    driver: bridge
